[package]
name = "todo-rust"
version = "0.1.0"
authors = ["jean.silva"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
